
    create table example (
        id integer generated by default as identity,
        description varchar(255),
        name varchar(255),
        primary key (id)
    );

    create table job (
        id integer generated by default as identity,
        description varchar(255),
        name varchar(255),
        primary key (id)
    );

    create table example (
        id bigint generated by default as identity,
        job_id bigint not null,
        product varchar(255),
        primary key (id)
    );

    create table job (
        id bigint generated by default as identity,
        name varchar(255),
        primary key (id)
    );

    alter table if exists example 
       add constraint FK9mlv2xchlnjhpavmxp93ro8rm 
       foreign key (job_id) 
       references job;
