version: '3.8'

services:
  backend:
    image: ghcr.io/arturo-08/java-starter-backend:latest
    container_name: backend-app
    ports:
      - "8080:8080"
    env_file: .env
    depends_on:
      - db
    restart: always
