
    create table example (
        id bigint generated by default as identity,
        job_id bigint not null,
        product varchar(255),
        primary key (id)
    );

    create table job (
        id bigint generated by default as identity,
        name varchar(255),
        primary key (id)
    );

    create table roles (
        id bigint generated by default as identity,
        description varchar(255),
        name varchar(255) not null unique,
        primary key (id)
    );

    create table users (
        enabled boolean not null,
        created_at timestamp(6),
        id bigint generated by default as identity,
        role_id bigint,
        updated_at timestamp(6),
        email varchar(255) not null unique,
        full_name varchar(255),
        password varchar(255) not null,
        primary key (id)
    );

    alter table if exists example 
       add constraint FK9mlv2xchlnjhpavmxp93ro8rm 
       foreign key (job_id) 
       references job;

    alter table if exists users 
       add constraint FKp56c1712k691lhsyewcssf40f 
       foreign key (role_id) 
       references roles;

    create table example (
        id bigint generated by default as identity,
        job_id bigint not null,
        product varchar(255),
        primary key (id)
    );

    create table job (
        id bigint generated by default as identity,
        name varchar(255),
        primary key (id)
    );

    create table roles (
        id bigint generated by default as identity,
        description varchar(255),
        name varchar(255) not null unique,
        primary key (id)
    );

    create table users (
        enabled boolean not null,
        created_at timestamp(6),
        id bigint generated by default as identity,
        role_id bigint,
        updated_at timestamp(6),
        email varchar(255) not null unique,
        full_name varchar(255),
        password varchar(255) not null,
        primary key (id)
    );

    alter table if exists example 
       add constraint FK9mlv2xchlnjhpavmxp93ro8rm 
       foreign key (job_id) 
       references job;

    alter table if exists users 
       add constraint FKp56c1712k691lhsyewcssf40f 
       foreign key (role_id) 
       references roles;

    create table example (
        id bigint generated by default as identity,
        job_id bigint not null,
        product varchar(255),
        primary key (id)
    );

    create table job (
        id bigint generated by default as identity,
        name varchar(255),
        primary key (id)
    );

    create table roles (
        id bigint generated by default as identity,
        description varchar(255),
        name varchar(255) not null unique,
        primary key (id)
    );

    create table users (
        enabled boolean not null,
        created_at timestamp(6),
        id bigint generated by default as identity,
        role_id bigint,
        updated_at timestamp(6),
        email varchar(255) not null unique,
        full_name varchar(255),
        password varchar(255) not null,
        primary key (id)
    );

    alter table if exists example 
       add constraint FK9mlv2xchlnjhpavmxp93ro8rm 
       foreign key (job_id) 
       references job;

    alter table if exists users 
       add constraint FKp56c1712k691lhsyewcssf40f 
       foreign key (role_id) 
       references roles;

    create table example (
        id bigint generated by default as identity,
        job_id bigint not null,
        product varchar(255),
        primary key (id)
    );

    create table job (
        id bigint generated by default as identity,
        name varchar(255),
        primary key (id)
    );

    create table roles (
        id bigint generated by default as identity,
        description varchar(255),
        name varchar(255) not null unique,
        primary key (id)
    );

    create table users (
        enabled boolean not null,
        created_at timestamp(6),
        id bigint generated by default as identity,
        role_id bigint,
        updated_at timestamp(6),
        email varchar(255) not null unique,
        full_name varchar(255),
        password varchar(255) not null,
        primary key (id)
    );

    alter table if exists example 
       add constraint FK9mlv2xchlnjhpavmxp93ro8rm 
       foreign key (job_id) 
       references job;

    alter table if exists users 
       add constraint FKp56c1712k691lhsyewcssf40f 
       foreign key (role_id) 
       references roles;

    create table example (
        id bigint generated by default as identity,
        job_id bigint not null,
        product varchar(255),
        primary key (id)
    );

    create table job (
        id bigint generated by default as identity,
        name varchar(255),
        primary key (id)
    );

    create table roles (
        id bigint generated by default as identity,
        description varchar(255),
        name varchar(255) not null unique,
        primary key (id)
    );

    create table users (
        enabled boolean not null,
        created_at timestamp(6),
        id bigint generated by default as identity,
        role_id bigint,
        updated_at timestamp(6),
        email varchar(255) not null unique,
        full_name varchar(255),
        password varchar(255) not null,
        primary key (id)
    );

    alter table if exists example 
       add constraint FK9mlv2xchlnjhpavmxp93ro8rm 
       foreign key (job_id) 
       references job;

    alter table if exists users 
       add constraint FKp56c1712k691lhsyewcssf40f 
       foreign key (role_id) 
       references roles;

    create table example (
        id bigint generated by default as identity,
        job_id bigint not null,
        product varchar(255),
        primary key (id)
    );

    create table job (
        id bigint generated by default as identity,
        name varchar(255),
        primary key (id)
    );

    create table roles (
        id bigint generated by default as identity,
        description varchar(255),
        name varchar(255) not null unique,
        primary key (id)
    );

    create table users (
        enabled boolean not null,
        created_at timestamp(6),
        id bigint generated by default as identity,
        role_id bigint,
        updated_at timestamp(6),
        email varchar(255) not null unique,
        full_name varchar(255),
        password varchar(255) not null,
        primary key (id)
    );

    alter table if exists example 
       add constraint FK9mlv2xchlnjhpavmxp93ro8rm 
       foreign key (job_id) 
       references job;

    alter table if exists users 
       add constraint FKp56c1712k691lhsyewcssf40f 
       foreign key (role_id) 
       references roles;

    create table example (
        id bigint generated by default as identity,
        job_id bigint not null,
        product varchar(255),
        primary key (id)
    );

    create table job (
        id bigint generated by default as identity,
        name varchar(255),
        primary key (id)
    );

    create table roles (
        id bigint generated by default as identity,
        description varchar(255),
        name varchar(255) not null unique,
        primary key (id)
    );

    create table users (
        enabled boolean not null,
        created_at timestamp(6),
        id bigint generated by default as identity,
        role_id bigint,
        updated_at timestamp(6),
        email varchar(255) not null unique,
        full_name varchar(255),
        password varchar(255) not null,
        primary key (id)
    );

    alter table if exists example 
       add constraint FK9mlv2xchlnjhpavmxp93ro8rm 
       foreign key (job_id) 
       references job;

    alter table if exists users 
       add constraint FKp56c1712k691lhsyewcssf40f 
       foreign key (role_id) 
       references roles;

    create table example (
        id bigint generated by default as identity,
        job_id bigint not null,
        product varchar(255),
        primary key (id)
    );

    create table job (
        id bigint generated by default as identity,
        name varchar(255),
        primary key (id)
    );

    create table roles (
        id bigint generated by default as identity,
        description varchar(255),
        name varchar(255) not null unique,
        primary key (id)
    );

    create table users (
        enabled boolean not null,
        created_at timestamp(6),
        id bigint generated by default as identity,
        role_id bigint,
        updated_at timestamp(6),
        email varchar(255) not null unique,
        full_name varchar(255),
        password varchar(255) not null,
        primary key (id)
    );

    alter table if exists example 
       add constraint FK9mlv2xchlnjhpavmxp93ro8rm 
       foreign key (job_id) 
       references job;

    alter table if exists users 
       add constraint FKp56c1712k691lhsyewcssf40f 
       foreign key (role_id) 
       references roles;

    create table example (
        id bigint generated by default as identity,
        job_id bigint not null,
        product varchar(255),
        primary key (id)
    );

    create table job (
        id bigint generated by default as identity,
        name varchar(255),
        primary key (id)
    );

    create table roles (
        id bigint generated by default as identity,
        description varchar(255),
        name varchar(255) not null unique,
        primary key (id)
    );

    create table users (
        enabled boolean not null,
        created_at timestamp(6),
        id bigint generated by default as identity,
        role_id bigint,
        updated_at timestamp(6),
        email varchar(255) not null unique,
        full_name varchar(255),
        password varchar(255) not null,
        primary key (id)
    );

    alter table if exists example 
       add constraint FK9mlv2xchlnjhpavmxp93ro8rm 
       foreign key (job_id) 
       references job;

    alter table if exists users 
       add constraint FKp56c1712k691lhsyewcssf40f 
       foreign key (role_id) 
       references roles;

    create table example (
        id bigint generated by default as identity,
        job_id bigint not null,
        product varchar(255),
        primary key (id)
    );

    create table job (
        id bigint generated by default as identity,
        name varchar(255),
        primary key (id)
    );

    create table roles (
        id bigint generated by default as identity,
        description varchar(255),
        name varchar(255) not null unique,
        primary key (id)
    );

    create table users (
        enabled boolean not null,
        created_at timestamp(6),
        id bigint generated by default as identity,
        role_id bigint,
        updated_at timestamp(6),
        email varchar(255) not null unique,
        full_name varchar(255),
        password varchar(255) not null,
        primary key (id)
    );

    alter table if exists example 
       add constraint FK9mlv2xchlnjhpavmxp93ro8rm 
       foreign key (job_id) 
       references job;

    alter table if exists users 
       add constraint FKp56c1712k691lhsyewcssf40f 
       foreign key (role_id) 
       references roles;
