name: CD - Deploy to EC2

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
    inputs:
      environment:
        description: Environment to deploy
        type: choice
        options:
          - 'DEV'
          - 'PROD'
        required: true
        default: 'DEV'

jobs:
  continuos_integration:
    uses: ./.github/workflows/ci-workflow-backend.yaml
    secrets: inherit

  continuos-deployment:
    environment: ${{ inputs.enviroment || 'DEV' }}
    runs-on: ubuntu-latest
    needs: continuos_integration
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Copy docker-compose to EC2
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ec2-user
          key: ${{ secrets.EC2_KEY }}
          source: "deploy/docker-compose.yml"
          target: "backend/"

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ec2-user
          key: ${{ secrets.EC2_KEY }}
          script: |
            cd backend/
            echo "${{ secrets.GHCR_PASSWORD }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
            docker compose pull
            docker compose up -d --remove-orphans
