name: CI - Build and Push Docker Image

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    environment: ${{ github.ref == 'refs/heads/main' && 'DEV' || 'PROD' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Build with Maven
        run: mvn clean package -DskipTests

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{ secrets.GHCR_PASSWORD }}

      - name: Build Docker image
        run: |
          IMAGE_ID=ghcr.io/arturo-08/java-starter-backend
          VERSION=sha-${GITHUB_SHA::7}
          docker build -t $IMAGE_ID:latest -t $IMAGE_ID:$VERSION .

      - name: Push Docker image
        run: |
          docker push ghcr.io/arturo-08/java-starter-backend:latest
          docker push ghcr.io/arturo-08/java-starter-backend:sha-${GITHUB_SHA::7}
